version: '3.9'
services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    ports:
      - 8080:8080
    volumes:
      - web:/app
  db:
    image: postgres:alpine
    restart: always
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - 5432:5432
    volumes:
      - db:/var/lib/postgresql/data
volumes:
  web:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: .
  db: